config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/goats", to: "goats#index"

  resources :markers

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/marker.rb
class Marker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goats_controller.rb
class GoatsController < ApplicationController
  def index
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: %i[ show edit update destroy ]

  # GET /markers or /markers.json
  def index
    @markers = Marker.all
  end

  # GET /markers/1 or /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers or /markers.json
  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to marker_url(@marker), notice: "Marker was successfully created." }
        format.json { render :show, status: :created, location: @marker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1 or /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to marker_url(@marker), notice: "Marker was successfully updated." }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1 or /markers/1.json
  def destroy
    @marker.destroy

    respond_to do |format|
      format.html { redirect_to markers_url, notice: "Marker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:marker).permit(:name, :description, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goats_helper.rb
module GoatsHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goats/index.html.erb
<h1>Goats#index</h1>
<p>Find me in app/views/goats/index.html.erb</p>

<p>
    <ul>
        <li>FQDN: <%= ENV['FQDN'] %></li>
    </ul>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nologo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/topnav" %>
    <div class="container-fluid mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/markers/_form.html.erb
<%= form_with(model: marker) do |form| %>
  <% if marker.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
        <% marker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/markers/_marker.html.erb
<div id="<%= dom_id marker %>">

  <div class="d-flex border border-5 border-dark align-items-center mb-5">

    <div class="flex-shrink-0 m-4">
      <img src="/pin_drop_black_48dp.svg" alt="...">
    </div>
    <div class="flex-grow-1">
      <%= link_to marker.name, marker %><br>
      <%= marker.description %><br>
      <%= marker.status %>
    </div>

  </div>


</div>

app/views/markers/edit.html.erb
<h1>Editing marker</h1>

<%= render "form", marker: @marker %>

<br>

<div>
  <%= link_to "Show this marker", @marker %> |
  <%= link_to "Back to markers", markers_path %>
</div>

app/views/markers/index.html.erb
<div class="row">
  <div class="col">

    <p style="color: green"><%= notice %></p>

    <div class="row mb-3">
      <div class="col">
        <span class="h3"><%= @markers.count %> Markers</span>
      </div>
      <div class="d-flex col justify-content-end">
        <%= link_to "New marker", new_marker_path, class: 'btn btn-dark' %>
      </div>
    </div>

    <div id="markers">

      <% @markers.each do |marker| %>
        <%= render marker %>
      <% end %>

    </div>

  </div>
</div>

app/views/markers/new.html.erb
<h1>New marker</h1>

<%= render "form", marker: @marker %>

<br>

<div>
  <%= link_to "Back to markers", markers_path %>
</div>

app/views/markers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @marker %>

<div>
  <%= link_to "Edit this marker", edit_marker_path(@marker) %> |
  <%= link_to "Back to markers", markers_path %>

  <%= button_to "Destroy this marker", @marker, method: :delete %>
</div>

app/views/shared/_topnav.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to "nologo", root_path, class: 'navbar-brand fst-italic', aria: {disabled:'false'} %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Markers", markers_path, class: 'nav-link', aria: {disabled:'false'} %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="row mt-5">
  <div class="col text-center mt-5">
    <img src="/images/PortainerTM-blue-landscape-small-web-no-crane.png">
  </div>
</div>